apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sn-java-demo-trigger.fullname" . }}
spec:
  maxReplicas: {{ .Values.scale.max }}
  minReplicas: {{ .Values.scale.min }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: sn-java-demo
  targetCPUUtilizationPercentage: {{ .Values.scale.cpu }}