{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sn-java-demo.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $ingressHosts := .Values.ingress.hosts -}}
{{- $servicePort := (index .Values.service.ports 0).port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
  {{- range $ingressHosts }}
    - {{ . | quote }}
  {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
{{- range $ingressHosts }}
  - {{ . | quote }}
{{- end }}
  gateways:
  - {{ $fullName }}-gateway
  http:
  - match:
{{- range $ingressPaths }}
    - uri: 
        prefix: {{ . }}       
{{- end }}
    rewrite:
      uri: "/"
    retries:
          attempts: 3
          perTryTimeout: 1s
          retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes 
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $servicePort }}
{{- end }}