apiVersion: v1
kind: Service
metadata:
  name: {{ include "sn-java-demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sn-java-demo.name" . }}
    helm.sh/chart: {{ include "sn-java-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ range .Values.service.ports }}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
    name: {{ .name }}
    {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "sn-java-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
